### ISSUE TITLE
About scene_scale

### ISSUE THREAD

**Issue by xiangcai8** [Ruyi-Zha/r2_gaussian#16]
Hi !
In your code, you scale the scene so that the volume of interest is in [-1, 1]^3 cube. Could you give me some suggestions if I want to generate a scene in its original size.
<img width="509" alt="f1f2f1539aca5586f31c389368a8a28" src="https://github.com/user-attachments/assets/faf2c01e-e70f-4ff4-a79c-0d17701755ec">

**Comment by Ruyi-Zha** [comment]
Hi, you can set `scene_scale=1.0` to retain the original size. Please note that scaling the scene doesn’t affect the final volume values. The scaling is done purely for numerical stability and to enable the use of consistent hyperparameters across different scenes.

**Comment by JixiangChen-Jimmy** [comment]
Hi, I also have questions regarding the scene scale, why the projection image value will be multiplied by the scene scale (in line 270 of dataset_readers.py)?

**Comment by Ruyi-Zha** [comment]
This is because the projection image is also related to world units, as it is the integration of density along the ray path. Therefore, we need to scale the projection accordingly to ensure the final volume values remain unaffected.

**Comment by povolann** [comment]
> This is because the projection image is also related to world units, as it is the integration of density along the ray path. Therefore, we need to scale the projection accordingly to ensure the final volume values remain unaffected.

Hi, I ran into a problem with training my own dataset of x-ray images, since I have different geometry, I use sVoxel=0.5, but that makes scene_scale=4. And as mentioned previously, it will rescale the image in image = np.load(image_path) * scene_scale. But I am confused, can you explain more why this is done? Shouldn't this be somehow related to the image size/shape? This way I am rescaling the image pixel intensity values, not the size.
Can you explain to me more in detail why are you doing it? Thank you!

**Comment by Ruyi-Zha** [comment]
Hi, we normalize the scene to a predefined box (sVoxel=2.0) so that we can share the same hyperparameters across different settings, but I think normalization is not strictly necessary. You can comment out normalization to see if the code still works. 

Regarding rescaling, we only want to adjust the scene size while keeping other properties, such as image resolution, unchanged. Since pixel values correspond to physical units (integration along the ray path), rescaling ensures consistency.

**Comment by immortalmin** [comment]
In this example, since the scene is scaled up (with sVoxel increased from 0.5 to 2.0, a scaling factor of 4), the size of each voxel is correspondingly enlarged to four times its original size. When calculating the projection image using a discrete method (as illustrated in the figure below), the length of each path also increases by a factor of 4, which results in the accumulated projection value being quadrupled as well.

<img width="226" alt="Image" src="https://github.com/user-attachments/assets/4786dd46-8a16-4e10-898a-8a92106e6910" />

To maintain numerical consistency with the original projection image, it is necessary to pre-scale the pixel values of the real projection image by a factor of 4 in the code, thereby compensating for the changes caused by the scene enlargement.

Is my understanding correct?

**Comment by povolann** [comment]
> Hi, we normalize the scene to a predefined box (sVoxel=2.0) so that we can share the same hyperparameters across different settings, but I think normalization is not strictly necessary. You can comment out normalization to see if the code still works.
> 
> Regarding rescaling, we only want to adjust the scene size while keeping other properties, such as image resolution, unchanged. Since pixel values correspond to physical units (integration along the ray path), rescaling ensures consistency.

Ok, I understand why you rescaled the scene. Thank you for your answer!
I tried to run the code without the rescaling while keeping other parameters the same, but then I ran out of memory for the final rendering (at it=30k) and the PSNR/SSIM is pretty similar.
But in both cases, I have these striking/hot spot-like artefacts. Is there any part/hyperparameter I should focus on regarding the training?

Original (with the scaling) (it=30k)
![Image](https://github.com/user-attachments/assets/4e03fe93-145b-4a78-a9d9-2969d5178217)

Without the scaling (it=20k)
![Image](https://github.com/user-attachments/assets/37de1446-3521-43b1-ba05-93b496db3b91)

**Comment by Ruyi-Zha** [comment]
The out-of-memory issue is likely related to densification. You may need to adjust d`ensify_grad_threshold` or disable densification entirely by setting `densify_until_iter=0`. I recommend disabling densification, as it should not cause a noticeable performance drop if there are a sufficient number of Gaussians.

In our experiments, we observed similar artifacts, which may indicate that some Gaussians overfit to a ray, causing them to become elongated. While we don't have a definitive solution yet, we mitigate this effect using TV regularization.
